### ISSUE TITLE
Automated Tool Ran on Codebase

### ISSUE THREAD

**Issue by Chrs987** [Chrs987/HomeAssistant#75]
Run Bandit on Code Bases and upload report to Github Repo

**Comment by Jbibianochavez** [comment]
The Report was added to /reports/results.csv. 
Summary:
- Code scanned:
   * Total lines of code: 410574
    * Total lines skipped (#nosec): 8
- Run metrics:
    * Total issues (by severity):
        * Undefined: 0.0
        * Low: 223.0
        * Medium: 7.0
        * High: 18.0
    * Total issues (by confidence):
        * Undefined: 0.0
        * Low: 0.0
        * Medium: 3.0
        * High: 245.0
- Files skipped (0):
